platform :ios, '9.0'
use_frameworks!

target 'ZJArmoire' do

pod 'Alamofire', '4.0.1'
pod 'SnapKit', '3.0.1'
pod 'Kingfisher', '3.1.3'
pod 'RxSwift', '3.0.1'
pod 'IQKeyboardManagerSwift', '4.0.7'
#pod 'UITableView+FDTemplateLayoutCell', '1.4'

#只在 DEBUG 模式下使用
pod 'DJDebug', :svn => "http://svn.djcorp.cn:8088/dianshangwuxian/trunk/mobile/jzt/ios/DJComponents/DJDebug", :configurations => ['Debug']
pod 'FLEX','2.1.1',:configurations => ['Debug']
pod 'InAppSettingsKit','2.8',:configurations => ['Debug']

end
